In [27]:
%pylab inline
from collections import Counter

Populating the interactive namespace from numpy and matplotlib


In [36]:
data = [
    (0,0),
    (0,1),
    (1,1),
    (1,0),
    (0,1),
    (1,1),
    (1,1)
]


# unique labels in our set
# this will hold the references for the label indicies.
unique_labels = np.unique(labels) 
labels_array = np.array(labels)
data_array = np.array(data) # the data in array format

n = data_array.shape[0] # number of observations we have
m = data_array.shape[1] # number of features
k = len(unique_labels) # number of classes


In [30]:
num_y = Counter(labels)
print num_y

Counter({0: 4, 1: 3})


In [33]:
positive_labeled_data = data_array[labels_array == 1]
print positive_labeled_data

[[0 1]
 [1 0]
 [0 1]]


In [34]:
negative_labeled_data = data_array[labels_array == 0]

In [37]:
P = {}
for label in unique_labels:
    P[label] = {}

In [41]:
for feature_index, feature_distribution in enumerate(data_array.T):
    for label in unique_labels:
        P[label][feature_index] = Counter(feature_distribution)
    

In [42]:
P

{0: {0: Counter({0: 3, 1: 4}), 1: Counter({0: 2, 1: 5})},
 1: {0: Counter({0: 3, 1: 4}), 1: Counter({0: 2, 1: 5})}}

In [14]:
P = {
    Label1: {
        feature1: {
            value1:0,
            value2:1
        }
    },
    Label2: {
        feature1:{
            value1:0,
            value2:1
        }
    }
}

array([0, 0, 1, 1, 0, 1, 1])

In [43]:
from sklearn.feature_extraction import DictVectorizer

In [49]:
import pandas as pd

In [166]:
training = [['Drew', 0, 1, 0, 0],
['Claudia', 1, 0, 1, 1],
['Drew', 0, 1, 1, 1],
['Drew', 0, 1, 1, 1],
['Alberto', 1, 0, 0, 0],
['Karin', 0, 1, 1, 1],
['Nina', 1, 0, 0, 1],
['Sergio', 1, 1, 1 ,0]]          

df = pd.DataFrame(training)
df.columns = ['Name', 'isOver170', 'isEyeBlue', 'isHairLong', 'isFemaleFeature']
MYDICT = df.to_dict('records')
vec = DictVectorizer()
dataset = vec.fit_transform(MYDICT).toarray()

# target labels
isFemale = np.array([0, 1, 1, 1, 0, 1, 1])

In [172]:
df

Name  isOver170  isEyeBlue  isHairLong  isFemaleFeature
0     Drew          0          1           0                0
1  Claudia          1          0           1                1
2     Drew          0          1           1                1
3     Drew          0          1           1                1
4  Alberto          1          0           0                0
5    Karin          0          1           1                1
6     Nina          1          0           0                1
7   Sergio          1          1           1                0

$$P(Y~|~X) = \frac{P(X~|~Y) P(Y)}{P(X)} = \frac{P(Y) \prod_{j=1}^n P(X_j~|~Y) }{P(X)}$$

$$\frac{P(Y = 1 | X)}{P(Y=0 | X)} = \frac{P(Y=1) \prod_{j=1}^n P(X_j~|~Y=1) }{P(Y=0) \prod_{j=1}^n P(X_j~|~Y=0)}$$

In [165]:
isFemale

array([0, 1, 1, 1, 0, 1, 1, 0])

In [138]:
N_0, N_1 = np.sum(isFemale == 0), np.sum(isFemale == 1)
N_total = N_0 + N_1

P_y = [ N_0/float(N_total) , N_1/float(N_total)]

In [139]:
P_y

[0.375, 0.625]

In [143]:
male_features = dataset[isFemale == 0]
print male_features

[[ 0.  0.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.  1.  1.]]


In [176]:
male_feature_densities = np.zeros(male_features.shape[1])
for feature_index, feature_values in enumerate(male_features.T):
    print 'j=',feature_index, 'value:', feature_values
    print 'density:',np.sum(feature_values)/N_0
    male_feature_densities[feature_index] = np.sum(feature_values)/N_0

j= 0 value: [ 0.  1.  0.]
density: 0.333333333333
j= 1 value: [ 0.  0.  0.]
density: 0.0
j= 2 value: [ 1.  0.  0.]
density: 0.333333333333
j= 3 value: [ 0.  0.  0.]
density: 0.0
j= 4 value: [ 0.  0.  0.]
density: 0.0
j= 5 value: [ 0.  0.  1.]
density: 0.333333333333
j= 6 value: [ 1.  0.  1.]
density: 0.666666666667
j= 7 value: [ 0.  0.  0.]
density: 0.0
j= 8 value: [ 0.  0.  1.]
density: 0.333333333333
j= 9 value: [ 0.  1.  1.]
density: 0.666666666667


In [177]:
female_features = dataset[isFemale == 1]
print 'subset of data:'
print female_features
print '---'
female_feature_densities = np.zeros(female_features.shape[1])
for feature_index, feature_values in enumerate(female_features.T):
    print 'j=',feature_index, 'value:', feature_values
    print 'density:',np.sum(feature_values)/N_1
    female_feature_densities[feature_index] = np.sum(feature_values)/N_1

subset of data:
[[ 0.  1.  0.  0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  1.  0.  0.  0.  1.  1.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  1.  0.  1.]]
---
j= 0 value: [ 0.  0.  0.  0.  0.]
density: 0.0
j= 1 value: [ 1.  0.  0.  0.  0.]
density: 0.2
j= 2 value: [ 0.  1.  1.  0.  0.]
density: 0.4
j= 3 value: [ 0.  0.  0.  1.  0.]
density: 0.2
j= 4 value: [ 0.  0.  0.  0.  1.]
density: 0.2
j= 5 value: [ 0.  0.  0.  0.  0.]
density: 0.0
j= 6 value: [ 0.  1.  1.  1.  0.]
density: 0.6
j= 7 value: [ 1.  1.  1.  1.  1.]
density: 1.0
j= 8 value: [ 1.  1.  1.  1.  0.]
density: 0.8
j= 9 value: [ 1.  0.  0.  0.  1.]
density: 0.4


In [180]:
female_feature_densities

array([ 0. ,  0.2,  0.4,  0.2,  0.2,  0. ,  0.6,  1. ,  0.8,  0.4])

In [181]:
X_test = [0,1,0,0,0,0, 1,0,1,1]

In [187]:
X_test = np.array(X_test) 

In [194]:
np.multiply(1-X_test, male_feature_densities)

array([ 0.33333333,  0.        ,  0.33333333,  0.        ,  0.        ,
        0.33333333,  0.        ,  0.        ,  0.        ,  0.        ])

In [195]:
np.multiply(X_test, female_feature_densities)

array([ 0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0.6,  0. ,  0.8,  0.4])

In [193]:
1-X_test

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [191]:
np.multiply(1-X_test, male_feature_densities) + np.multiply(X_test, female_feature_densities)

array([ 0.33333333,  0.2       ,  0.33333333,  0.        ,  0.        ,
        0.33333333,  0.6       ,  0.        ,  0.8       ,  0.4       ])